Settings:
  type: entity
  table: settings
  fields:
    idsetting:
      id: true
      type: integer
      unsigned: false
      nullable: false
      generator:
        strategy: IDENTITY
    name:
      type: text
      nullable: false
    value:
      type: text
      nullable: false
  lifecycleCallbacks: {  }
