entry:
    pattern:  /
    defaults: { _controller: "BlueCMSBundle:Entry:index" }

entry_show:
    pattern:  /{id}/show
    defaults: { _controller: "BlueCMSBundle:Entry:show" }

entry_new:
    pattern:  /new
    defaults: { _controller: "BlueCMSBundle:Entry:new" }

entry_create:
    pattern:  /create
    defaults: { _controller: "BlueCMSBundle:Entry:create" }
    requirements: { _method: post }

entry_edit:
    pattern:  /{id}/edit
    defaults: { _controller: "BlueCMSBundle:Entry:edit" }

entry_update:
    pattern:  /{id}/update
    defaults: { _controller: "BlueCMSBundle:Entry:update" }
    requirements: { _method: post }

entry_delete:
    pattern:  /{id}/delete
    defaults: { _controller: "BlueCMSBundle:Entry:delete" }
    requirements: { _method: post }
